# Organization and project keys are displayed in the right sidebar of the project homepage
sonar.organization=karya-lepas-apps-1
sonar.projectKey=rona-dinihari_node-tesseract

# Use ONLY if you have a scanner version smaller than 6.0
sonar.host.url=https://sonarcloud.io

# --- optional properties ---

# Must be set if you want to use SonarQube Cloud's US instance. Defaults to empty, which corresponds to EU instance
# sonar.region=us

# defaults to project key
# sonar.projectName=My project
# defaults to 'not provided'
# sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Defaults to .
# sonar.sources=.

# Encoding of the source code. Default is default system encoding
# sonar.sourceEncoding=UTF-8